# Copyright 2020, Cray Inc.
---
apiVersion: v2
name: cray-nexus
version: 0.9.1
description: Sonatype Nexus is an open source repository manager
keywords:
  - sonatype
  - nexus
  - repository
  - management
home: https://github.com/Cray-HPE/cray-nexus
sources:
  - https://github.com/Oteemo/charts
dependencies:
  - name: sonatype-nexus
    version: 2.3.1
    repository: https://oteemo.github.io/charts/
maintainers:
  - name: rnoska-hpe
icon: https://raw.githubusercontent.com/sonatype/nexus-public/release-3.25.0-03/components/nexus-rapture/src/main/resources/static/rapture/resources/icons/x100/nexus-black.png
appVersion: 3.25.0
annotations:
  artifacthub.io/license: MIT
