#
# MIT License
#
# (C) Copyright 2020-2025 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
---
apiVersion: v2
name: cray-nexus
version: 0.14.0
description: Sonatype Nexus is an open source repository manager
keywords:
  - sonatype
  - nexus
  - repository
  - management
home: https://github.com/Cray-HPE/cray-nexus
sources:
  - https://github.com/Oteemo/charts
dependencies:
  - name: sonatype-nexus
    version: 2.3.1
    repository: https://oteemo.github.io/charts/
maintainers:
  - name: rnoska-hpe
icon: https://raw.githubusercontent.com/sonatype/nexus-public/main/components/nexus-rapture/src/main/resources/static/rapture/resources/icons/x100/nexus-black.png
appVersion: 3.70.4
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/images: |
    - name: nexus3
      image: artifactory.algol60.net/csm-docker/stable/docker.io/sonatype/nexus3:3.70.4
