#
# MIT License
#
# (C) Copyright 2020-2024 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#

# Example Nexus Repository Manager (NXRM) configuration that adds proxy and
# group "docker" repositories to the default airgap setup provided by
# cray-nexus-setup.
schema: v2
name: nexus
version: 1.0.0
repositories:
  docker: registry.local
  helm: charts.local
failOnFirstError: true
charts:
- name: cray-nexus
  version: 0.4.0
  namespace: nexus
  values:
    sonatype-nexus:
      service:
        ports:
        # Port for "registry.local" group repository added below
        - name: group-registry
          port: 5000
          targetPort: 5000
        # Port for the default registry
        - name: default-registry
          port: 5003
          targetPort: 5003
    istio:
      ingress:
        hosts:
          registry:
            routes:
              # Writes goto port 5003 (default registry). NXRM does not (as of
              # yet) support pushing to group repositories, see
              # https://issues.sonatype.org/browse/NEXUS-10471. Until then, a
              # port must be exposed in order to enable images to be pushed to
              # this registry. See also, https://stackoverflow.com/a/54590014
              # which describes using a reverse proxy to direct writes to the
              # desired registry.
              - match:
                - method:
                    exact: HEAD
                  uri:
                    regex: "^/v(1|2)/.*/blobs/sha256:[A-Fa-f0-9]{64}$"
                - method:
                    exact: POST
                - method:
                    exact: PUT
                - method:
                    exact: PATCH
                - method:
                    exact: DELETE
                port: 5003
                headers:
                  request:
                    add:
                      X-WEBAUTH-USER: admin
                    remove:
                    - Authorization
              # Reads goto port 5000 (group registry)
              - port: 5000
                headers:
                  request:
                    add:
                      X-WEBAUTH-USER: admin
                    remove:
                    - Authorization
          ui:
            authority: nexus.drax.dev.cray.com
            enabled: true

# Corresponding overrides for cray-nexus-setup to illustrate push/pull to/from
# a registry group with a hosted member.
- name: cray-nexus-setup
  version: 0.1.0
  namespace: nexus
  values:
    additionalRepositories:
    # Proxy registry to dtr.dev.cray.com
    - name: dtr.dev.cray.com
      format: docker
      storage:
        blobStoreName: latest
        writePolicy: ALLOW
      proxy:
        remoteUrl: https://dtr.dev.cray.com/
    # Group registry to pull from the default registry and dtr.dev.cray.com
    - name: registry.local
      format: docker
      storage:
        blobStoreName: latest
      group:
        memberNames:
        - default-registry
        - dtr.dev.cray.com
      docker:
        # Corresponds to the group-registry port defined in cray-nexus.service
        httpPort: 5000
