#
# MIT License
#
# (C) Copyright 2020-2025 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#

# Base sonatype-nexus chart values
# See https://github.com/Oteemo/charts/tree/master/charts/sonatype-nexus#configuration
# for Nexus base chart configuration information
sonatype-nexus:

  # These overrides are very, very critical as it enables the "init"
  # initContainer (see below) to be able to correctly mount the nexus-data
  # volume in order to successfully initialize it.
  nameOverride: nexus
  fullnameOverride: nexus

  deploymentStrategy:
    type: Recreate

  nexus:
    priorityClassName: "csm-high-priority-service"
    imageName: artifactory.algol60.net/csm-docker/stable/docker.io/sonatype/nexus3
    imageTag: 3.70.4
    env:
    # See https://help.sonatype.com/repomanager3/installation/system-requirements#SystemRequirements-Memory
    - name: INSTALL4J_ADD_VM_PARAMS
      value: "-Xms4G -Xmx4G -XX:MaxDirectMemorySize=39158M -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djavax.net.ssl.trustStore=/nexus-data/cacerts"
    - name: NEXUS_SECURITY_RANDOMPASSWORD
      value: "false"
    resources:
      requests:
        cpu: 500m
        memory: 12Gi
      limits:
        cpu: "12"
        memory: 64Gi
    podAnnotations:
      sidecar.istio.io/proxyCPULimit: "8"
      sidecar.istio.io/proxyMemoryLimit: "16Gi"

  persistence:
    enabled: true
    storageClass: ceph-cephfs-external
    accessMode: ReadWriteMany
    storageSize: 1000Gi
    annotations:
      helm.sh/resource-policy: keep

  deployment:
    additionalVolumes:
    - name: nexus-config
      configMap:
        name: nexus-config
    - name: keycloak-realm-config
      secret:
        secretName: nexus-keycloak-realm-config
    - name: ca-public-key
      configMap:
        name: cray-configmap-ca-public-key
    additionalVolumeMounts:
    - name: keycloak-realm-config
      mountPath: /opt/sonatype/nexus/etc/keycloak.json
      subPath: keycloak.json
      readOnly: true
    - name: ca-public-key
      mountPath: /ca_public_key
    initContainers:
    - name: init
      image: artifactory.algol60.net/csm-docker/stable/docker.io/sonatype/nexus3:3.70.4
      command:
      - /bin/sh
      - -c
      - |
        if [ -z "$(ls -A /nexus-data/*)" ]; then
            mkdir -p /nexus-data/etc
            cp /nexus-config/nexus.properties /nexus-data/etc/nexus.properties
            chown -Rv 200:200 /nexus-data
            chmod -Rv u+rwX,go+rX,go-w /nexus-data
        fi
        # Always start with a fresh trust store
        rm -f /nexus-data/cacerts
        # Create new trust store with all /ca_public_key certs
        /usr/local/bin/create-trust-store.sh /nexus-data/cacerts /ca_public_key/*
        # Update owner
        chown -v 200:200 /nexus-data/cacerts
        # Remove write permissions
        chmod -v ugo-w /nexus-data/cacerts
      volumeMounts:
      - name: nexus-data  # See the above note regarding nameOverride and fullnameOverride
        mountPath: /nexus-data
      - name: nexus-config
        mountPath: /nexus-config
      - name: ca-public-key
        mountPath: /ca_public_key

  service:
    enabled: true
    name: nexus
    portName: nexus
    port: 80
    targetPort: 8081
    ports:
    - name: default-registry
      port: 5003
      targetPort: 5003
    annotations:
      metallb.universe.tf/address-pool: node-management

  nexusProxy:
    enabled: false

  nexusBackup:
    persistence:
      enabled: false

# additionalServices:  # For testing only when no keycloak is around
#   # Do not use the key "service". It is reserved for the service included in
#   # sonatype-nexus.
#   can:
#     enabled: true
#     type: LoadBalancer
#     annotations:
#       external-dns.alpha.kubernetes.io/hostname: nexus.local
#       metallb.universe.tf/address-pool: customer-access

istio:
  enabled: true
  ingress:
    gateway:
    - "services/services-gateway"
    - "services/customer-admin-gateway"
    hosts:
      # NOTE Specifically remove the X-WEBAUTH-USER header to prevent previous
      # Nexus configurations from automatically authenticating clients.
      packages:
        enabled: true
        authority: packages.local
        routes:
        - port: 80
          headers:
            request:
              remove:
              - X-WEBAUTH-USER
      registry:
        enabled: true
        authority: registry.local
        routes:
        - port: 5003
          headers:
            request:
              remove:
              - X-WEBAUTH-USER
      ui:
        enabled: false
        authority: nexus.local
        routes:
        - port: 80
          headers:
            request:
              remove:
              - X-WEBAUTH-USER

setup:
  enabled: true
  image:
    repository: artifactory.algol60.net/csm-docker/stable/cray-nexus-setup
    tag: 0.11.1
    pullPolicy: IfNotPresent
  adminCredential:
    enabled: true
    secret: nexus-admin-credential

hooks:
  preInstall:
    image:
      repository: artifactory.algol60.net/csm-docker/stable/docker-kubectl
      tag: 1.24.17
      pullPolicy: IfNotPresent
    serviceAccountName: nexus-pre-install

security:
  anonymousAccess:
    enabled: true
  rutAuth:  # Remote User Token (RUT) Authentication
    enabled: false
    httpHeader: X-WEBAUTH-USER
  docker:
    enabled: true
  keycloak:
    enabled: true
    secretName: nexus-keycloak-realm-config  # See volume mount above
    config:
      realm: shasta
      auth-server-url: https://api-gw-service-nmn.local/keycloak  # $secret.endpoint
      ssl-required: external
      resource: system-nexus-client  # $secret.client-id
      verify-token-audience: true
      credentials:
        secret: null  # $secret.client-secret, defaults to a new UUID
      use-resource-role-mappings: true
      confidential-port: 0
      policy-enforcer: {}
    client:
      # Kubernetes secret (from Keycloak setup) expected to contain endpoint,
      # client-id, and client-secret data which overrides auth-server-url,
      # resource, and credentials.secret configs.
      secret:
        name: system-nexus-client-auth
        # namespace defaults to .Release.Namespace

sealedSecrets: []
